# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            William Jones
tagline:          'Lorem ipsum'
description:      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac purus massa. Nulla vel elit feugiat, rhoncus diam sed, varius diam. Donec eleifend pretium nibh.'
url:              lewisdbentley.github.io
baseurl:          'will_jones'

author:
  name:           'Lewis Bentley'
  url:            https://github.com/lewisdbentley

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lewisdbentley/will_jones

plugins:
  - jekyll-paginate
  - jekyll-gist

# Collections

collections:
  art:
    output: true
  music:
    output: true

collections_dir: my_collections